# Generated by Django 6.0.1 on 2026-01-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand_avto', models.CharField(max_length=100)),
                ('engine_capacity', models.PositiveSmallIntegerField(help_text='m3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=100)),
                ('year_manufacture', models.PositiveSmallIntegerField()),
                ('body_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars_images/')),
                ('available', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10)),
            ],
        ),
    ]
