# Generated by Django 6.0.1 on 2026-01-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.FloatField(help_text='m3'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='$', max_digits=10),
        ),
    ]
